---
title: "Gapminder-hw01"
author: "Aisha Uduman"
date: "9/18/2017"
output:
  html_document: default
  github_document:
    keep_md: yes
---

#R Markdown for Homework 1 

Exploring gapminder. 

- Polish and extend R Markdown doc from Sept 14 class 
- Render it to the github_document output format
- Commit both .Rmd and .md files and push them to Github


install.packages("gapminder")
install.packages("tidyverse")

library(gapminder)
library(tidyverse)


```{r}
p <- ggplot(filter(gapminder, continent != "Oceania"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point()
```

```{r}
table(gapminder$continent)
```

```{r}
barplot(table(gapminder$continent))
```


```{r}
p <- ggplot(filter(gapminder, country == "Chile"),
            aes(x = gdpPercap, y = year)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point()
```


```{r}
p <- ggplot(filter(gapminder, country == "Vietnam"),
            aes(x = gdpPercap, y = lifeExp)) # just initializes
p <- p + scale_x_log10() # log the x axis the right way
p + geom_point()
```


